version: "3"
services:
    pgvecto-rs:
        container_name: semse-db
        env_file:
            -   .env
        volumes:
            - ./db:/var/lib/postgresql/data
        networks:
            - semse_db_net
        image: tensorchord/pgvecto-rs:pg16-v0.2.1

    semse-api:
        build: server
        container_name: semse-api
        env_file:
            - .env
        ports:
            - "8822:8000"
        volumes:
            - ./server:/app
            - "/mnt/MediaFiles/MediaFiles:/media"
        networks:
            - semse_db_net
        depends_on:
            - pgvecto-rs

networks:
    semse_db_net:
        driver: bridge
